options:
  install_sources:
    type: string
    default: ""
  listen_port:
    type: int
    default: 51820
    description: "UDP port to listen for peers on"
  server_tunnel_address:
    type: string
    default: "10.0.0.1/24"
    description: "Interface server address"
  client_tunnel_address:
    type: string
    default: "10.0.0.2/24"
    description: "Interface client address"
  server_public_address:
    type: string
    default: "192.168.85.1/24"
    description: "Interface client address"
  forward_interface:
    type: string
    default: "wg0"
    description: "Interface to forward packets on"
  save_config:
    type: boolean
    default: true
    description: "Configuration file should be saved on shutdown using the current status of the interface"
  wg_server:
    type: boolean
    default: false
    description: "Specify if the charm should be configured as a server ou client"
