"options":
  "extra_packages":
    "description": >
      Space separated list of extra deb packages to install.
    "type": "string"
    "default": ""
  "package_status":
    "default": "install"
    "type": "string"
    "description": >
      The status of service-affecting packages will be set to this
      value in the dpkg database. Valid values are "install" and "hold".
  "install_sources":
    "description": >
      List of extra apt sources, per charm-helpers standard
      format (a yaml list of strings encoded as a string). Each source
      may be either a line that can be added directly to
      sources.list(5), or in the form ppa:<user>/<ppa-name> for adding
      Personal Package Archives, or a distribution component to enable.
    "type": "string"
    "default": ""
  "install_keys":
    "description": >
      List of signing keys for install_sources package sources, per
      charmhelpers standard format (a yaml list of strings encoded as
      a string). The keys should be the full ASCII armoured GPG public
      keys. While GPG key ids are also supported and looked up on a
      keyserver, operators should be aware that this mechanism is
      insecure. null can be used if a standard package signing key is
      used that will already be installed on the machine, and for PPA
      sources where the package signing key is securely retrieved from
      Launchpad.
    "type": "string"
    "default": ""
  "listen_port":
    "type": "int"
    "default": !!int "51820"
    "description": "UDP port to listen for peers on"
  "server_address":
    "type": "string"
    "default": "10.0.0.1/24"
    "description": "Interface server address"
  "client_address":
    "type": "string"
    "default": "10.0.0.2/24"
    "description": "Interface client address"
  "forward_interface":
    "type": "string"
    "default": "wg0"
    "description": "Interface to forward packets on"
  "save_config":
    "type": "boolean"
    "default": !!bool "true"
    "description": "Configuration file should be saved on shutdown using the current\
      \ status of the interface"
  "wg_server":
    "type": "boolean"
    "default": !!bool "true"
    "description": "Specify if the charm should be configured as a server ou client"
